### ISSUE TITLE
ImportError  PYTHON 3.11                              

### ISSUE THREAD

**Issue by tercjak** [QuantFreedom1022/yt_videos#1]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 5
      2 import plotly.graph_objects as go
      4 from quantfreedom.enums import CandleBodyType
----> 5 from quantfreedom.helper_funcs import dl_ex_candles
      6 from quantfreedom.indicators.tv_indicators import rsi_tv
      8 np.set_printoptions(formatter={"float_kind": "{:0.2f}".format})

File G:\python3_11\Lib\site-packages\quantfreedom\helper_funcs.py:8
      6 from datetime import datetime
      7 from quantfreedom.enums import AccountState, DynamicOrderSettings, DynamicOrderSettingsArrays, OrderResult
----> 8 from quantfreedom.exchanges.apex_exchange.apex import Apex
      9 from quantfreedom.exchanges.binance_exchange.binance_us import BinanceUS
     10 from quantfreedom.exchanges.binance_exchange.binance_usdm import BinanceUSDM

File G:\python3_11\Lib\site-packages\quantfreedom\exchanges\apex_exchange\apex.py:1
----> 1 from quantfreedom.exchanges.apex_exchange.apex_github.http_private_stark_key_sign import HttpPrivateStark
      2 from quantfreedom.exchanges.apex_exchange.apex_github.http_public import HttpPublic
      3 from quantfreedom.exchanges.exchange import UNIVERSAL_TIMEFRAMES, Exchange

File G:\python3_11\Lib\site-packages\quantfreedom\exchanges\apex_exchange\apex_github\__init__.py:24
     21 import logging
     22 import requests
---> 24 from web3 import Web3
     25 from quantfreedom.exchanges.apex_exchange.apex_github.eth_signing import SignWithWeb3, SignOnboardingAction
     26 from quantfreedom.exchanges.apex_exchange.apex_github.eth_signing import SignWithKey

File G:\python3_11\Lib\site-packages\web3\__init__.py:6
      2 import warnings
      4 import pkg_resources
----> 6 from eth_account import (
      7     Account  # noqa: E402,
      8 )
      9 from web3.main import (
     10     Web3  # noqa: E402,
     11 )
     12 from web3.providers.eth_tester import (  # noqa: E402
     13     EthereumTesterProvider,
     14 )

File G:\python3_11\Lib\site-packages\eth_account\__init__.py:1
----> 1 from eth_account.account import (
      2     Account,
      3 )
      5 __all__ = ["Account"]

File G:\python3_11\Lib\site-packages\eth_account\account.py:59
     49 from eth_account.datastructures import (
     50     SignedMessage,
     51     SignedTransaction,
     52 )
     53 from eth_account.hdaccount import (
     54     ETHEREUM_DEFAULT_PATH,
     55     generate_mnemonic,
     56     key_from_seed,
     57     seed_from_mnemonic,
     58 )
---> 59 from eth_account.messages import (
     60     SignableMessage,
     61     _hash_eip191_message,
     62 )
     63 from eth_account.signers.local import (
     64     LocalAccount,
     65 )
     68 class Account(object):

File G:\python3_11\Lib\site-packages\eth_account\messages.py:26
     14 from eth_utils.curried import (
     15     ValidationError,
     16     keccak,
   (...)
     20     to_text,
     21 )
     22 from hexbytes import (
     23     HexBytes,
     24 )
---> 26 from eth_account._utils.structured_data.hashing import (
     27     hash_domain,
     28     hash_message as hash_eip712_message,
     29     load_and_validate_structured_message,
     30 )
     31 from eth_account._utils.validation import (
     32     is_valid_address,
     33 )
     35 text_to_bytes = text_if_str(to_bytes)

File G:\python3_11\Lib\site-packages\eth_account\_utils\structured_data\hashing.py:9
      4 import json
      5 from operator import (
      6     itemgetter,
      7 )
----> 9 from eth_abi import (
     10     encode_abi,
     11     is_encodable,
     12     is_encodable_type,
     13 )
     14 from eth_abi.grammar import (
     15     parse,
     16 )
     17 from eth_utils import (
     18     ValidationError,
     19     keccak,
     20     to_tuple,
     21     toolz,
     22 )

File G:\python3_11\Lib\site-packages\eth_abi\__init__.py:6
      2 import warnings
      4 import pkg_resources
----> 6 from eth_abi.abi import (  # NOQA
      7     decode,
      8     decode_abi,
      9     decode_single,
     10     encode,
     11     encode_abi,
     12     encode_single,
     13     is_encodable,
     14     is_encodable_type,
     15 )
     17 if sys.version_info[1] == 6:
     18     # reference setup.py -> python_requires
     19     warnings.warn(
     20         "eth-abi version 3.0.0 will no longer support Python 3.6",
     21         category=DeprecationWarning,
     22         stacklevel=2
     23     )

File G:\python3_11\Lib\site-packages\eth_abi\abi.py:1
----> 1 from eth_abi.codec import (
      2     ABICodec,
      3 )
      4 from eth_abi.registry import (
      5     registry,
      6 )
      8 default_codec = ABICodec(registry)

File G:\python3_11\Lib\site-packages\eth_abi\codec.py:16
      8 from eth_typing.abi import (
      9     Decodable,
     10     TypeStr,
     11 )
     12 from eth_utils import (
     13     is_bytes,
     14 )
---> 16 from eth_abi.decoding import (
     17     ContextFramesBytesIO,
     18     TupleDecoder,
     19 )
     20 from eth_abi.encoding import (
     21     TupleEncoder,
     22 )
     23 from eth_abi.exceptions import (
     24     EncodingError,
     25 )

File G:\python3_11\Lib\site-packages\eth_abi\decoding.py:14
      4 from typing import (
      5     Any,
      6 )
      8 from eth_utils import (
      9     big_endian_to_int,
     10     to_normalized_address,
     11     to_tuple,
     12 )
---> 14 from eth_abi.base import (
     15     BaseCoder,
     16     parse_tuple_type_str,
     17     parse_type_str,
     18 )
     19 from eth_abi.exceptions import (
     20     DecodingError,
     21     InsufficientDataBytes,
     22     NonEmptyPaddingBytes,
     23 )
     24 from eth_abi.utils.numeric import (
     25     TEN,
     26     abi_decimal_context,
     27     ceil32,
     28 )

File G:\python3_11\Lib\site-packages\eth_abi\base.py:7
      1 import functools
      3 from eth_typing.abi import (
      4     TypeStr,
      5 )
----> 7 from .grammar import (
      8     BasicType,
      9     TupleType,
     10     normalize,
     11     parse,
     12 )
     15 def parse_type_str(expected_base=None, with_arrlist=False):
     16     """
     17     Used by BaseCoder subclasses as a convenience for implementing the
     18     ``from_type_str`` method required by ``ABIRegistry``.  Useful if normalizing
     19     then parsing a type string with an (optional) expected base is required in
     20     that method.
     21     """

File G:\python3_11\Lib\site-packages\eth_abi\grammar.py:4
      1 import functools
      2 import re
----> 4 import parsimonious
      5 from parsimonious import (
      6     expressions,
      7 )
      9 from eth_abi.exceptions import (
     10     ABITypeError,
     11     ParseError,
     12 )

File G:\python3_11\Lib\site-packages\parsimonious\__init__.py:9
      1 """Parsimonious's public API. Import from here.
      2 
      3 Things may move around in modules deeper than this one.
      4 
      5 """
      6 from parsimonious.exceptions import (ParseError, IncompleteParseError,
      7                                      VisitationError, UndefinedLabel,
      8                                      BadGrammar)
----> 9 from parsimonious.grammar import Grammar, TokenGrammar
     10 from parsimonious.nodes import NodeVisitor, VisitationError, rule

File G:\python3_11\Lib\site-packages\parsimonious\grammar.py:14
     11 from six import (text_type, itervalues, iteritems, python_2_unicode_compatible, PY2)
     13 from parsimonious.exceptions import BadGrammar, UndefinedLabel
---> 14 from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
     15     Lookahead, Optional, ZeroOrMore, OneOrMore, Not, TokenMatcher,
     16     expression)
     17 from parsimonious.nodes import NodeVisitor
     18 from parsimonious.utils import evaluate_string

File G:\python3_11\Lib\site-packages\parsimonious\expressions.py:9
      1 """Subexpressions that make up a parsed grammar
      2 
      3 These do the parsing.
      4 
      5 """
      6 # TODO: Make sure all symbol refs are local--not class lookups or
      7 # anything--for speed. And kill all the dots.
----> 9 from inspect import getargspec
     10 import re
     12 from six import integer_types, python_2_unicode_compatible

ImportError: cannot import name 'getargspec' from 'inspect' (G:\python3_11\Lib\inspect.py)

**Comment by quantfreedom** [comment]
Install python 3.10.10
